name: ci
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8 pytest

      - name: Lint (flake8)
        run: flake8 .

      - name: Unit tests
        env:
          # Make tests independent of local env
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mailminder?sslmode=disable
          MAILMINDER_API_KEY: dev-key
        run: |
          # Spin up Postgres for tests
          docker run -d --name pg -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=mailminder -p 5432:5432 postgres:16-alpine
          # Wait for DB to be ready
          for i in {1..30}; do
            docker exec pg pg_isready -U postgres && break
            sleep 1
          done
          # Apply migrations if you have alembic in requirements; else skip
          if command -v alembic >/dev/null 2>&1; then alembic upgrade head; fi
          # Run tests
          pytest -q
